### ISSUE TITLE
Installasi gagal

### ISSUE THREAD

**Issue by ghost** [andryluthfi/indonesian-postag#1]
## [SOLVED]

kesalahan terletak pada hak akses linux, setelah saya hapus yang lama dan ganti baru, errornya jadi hilang.

---

Salam kenal, 
Saya mencoba utk installasi pos-tagger ini tp mengalami kegagalan. Berikut spesifikasi komputer saya:
- Linux Mint KDE - Rebecca - 32-bit
- Foma-0.9.17_Linux32 (PATH sudah diatur dan saya tes tidak ada masalah)
- morphind.v.1.4 (saya tes sesuai contoh tapi banyak sekali errornya)
## Perintah untuk testing morphind:

cat sample.txt | perl MorphInd.pl > sample.out 
## Output error dari morphind:

Collecting Vocabulary:
rm: cannot remove ‘/home/abdiansah/Aplikasi/POS’: No such file or directory
rm: cannot remove ‘Tag’: No such file or directory
rm: cannot remove ‘Indonesian’: No such file or directory
rm: cannot remove ‘-’: No such file or directory
rm: cannot remove ‘UI/indonesian-postag-master/morphind/cache-files/12389.tmp’: No such file or directory
Use of uninitialized value in concatenation (.) or string at MorphInd.pl line 280, <STDIN> line 13.
Use of uninitialized value in concatenation (.) or string at MorphInd.pl line 280, <STDIN> line 13.
Use of uninitialized value in concatenation (.) or string at MorphInd.pl line 280, <STDIN> line 13.
Use of uninitialized value in concatenation (.) or string at MorphInd.pl line 280, <STDIN> line 13.
Use of uninitialized value in concatenation (.) or string at MorphInd.pl line 280, <STDIN> line 13.
Use of uninitialized value in concatenation (.) or string at MorphInd.pl line 280, <STDIN> line 13.
Use of uninitialized value $CACHE{"lambaiDASHlambai"} in substitution (s///) at MorphInd.pl line 447, <STDIN> line 13.
Use of uninitialized value $CACHE{"kucingDASHkucing"} in substitution (s///) at MorphInd.pl line 447, <STDIN> line 13.
dst dst dst (banyak sekali)

kira2 apa yang salah ya? thanks

**Comment by andryluthfi** [comment]
Hai Abdiasah 
Sepertinya masalah terjadi ketika direktori absolut dari POS Tag ini mempunya karater spasi..

Dan morphind sepertinya tidak menangani hal tersebut.

**Comment by ghost** [comment]
barusan saya berhasil install eksekusi morphind... sekarang mau coba post-taggingnya... nanti kalo berhasil saya update.

**Comment by andryluthfi** [comment]
Ok, semoga sukses dengan percobaannya.

Silahkan sampaikan masalah yang ditemukan dengan senang hati kami akan coba bantu.

**Comment by ghost** [comment]
sip mas andry, post-taggingnya berjalan dgn lancar... nanti saya eksplorasi lagi, sekalian utk buat riset saya ttg Question Answering System. ada email atau twitter yg bisa dihubungi mas? thanks

**Comment by andryluthfi** [comment]
Saya ke email mas Abdiasah ya kontak dari saya dan partner saya

**Comment by ghost** [comment]
ok, ini email saya mas: abdiansah84@gmail.com
