### ISSUE TITLE
goto deprecated

### ISSUE THREAD

**Issue by usmir** [andryluthfi/indonesian-postag#2]
Apakah error seperti ini berpengaruh pada kinerja tagging?

> Use of "goto" to jump into a construct is deprecated at NER.pl line 89, <IN> line 16.
> ...
> Use of "goto" to jump into a construct is deprecated at Rule-BasedTagging.pl line 67, <IN> line 19.

Windows (x86)
ActivePerl 5.20.2

**Comment by famrashel** [comment]
Seharusnya tidak.
Itu bukan error, tetapi hanya warning dari system bahwa ada penggunaan statement "jump to" yang memang sengaja kami buat untuk handle EOF yang mungkin tidak terbaca.

**Comment by usmir** [comment]
Terima kasih. Namun percobaan saya tidak bisa mereplicate secara persis output yang ada. Kira-kira permasalahannya ada di mana ya?

> Fam     NNP
> sedang  JJ,CC,MD        JJ,CC,MD        rule-10
> membaca VB
> apakah  X
> skripsi X
> ...

Output lengkap: https://github.com/usmir/ipostag-outputs/commit/77807467aaa0648a9822fae160233dd315cd04ce

**Comment by famrashel** [comment]
Maksudnya me-replicate itu apa ya?
Saya kurang paham masalahnya di mana.

**Comment by usmir** [comment]
Maksudnya, saya tidak bisa menghasilkan output yang sama dengan output yang tersedia sebelumnya. Ini terkait dengan satu kata yang diberi tag X.

Output orisinal: outputs/res-0000000-resolved.txt 

> skripsi NN

Output percobaan saya: new folder (2)/res-[001]-resolved.txt

> skripsi X

Awalnya saya curiga dengan "statement warning 'goto'" lah yang menyebabkannya. Tapi ternyata bukan.

**Comment by famrashel** [comment]
Untuk Nomina, Ajektiva, dan Verba merupakan hasil anotasi dari module MorphInd.

Output yang tersedia sebelumnya tidak harus selalu jadi pedoman. Itu bisa saja hasil eksperimen kami :)

**Comment by usmir** [comment]
Pindah ke linux menyelesaikan semua
Terima kasih
